FROM python:3.12-slim

RUN apt-get update && apt-get install -y python3 python3-pip

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget unzip curl gnupg \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && dpkg -i google-chrome*.deb || apt-get -fy install \
    && rm google-chrome*.deb

# Install ChromeDriver 114.0.5735.90
RUN wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip \
    && unzip /tmp/chromedriver.zip -d /usr/local/bin/ \
    && chmod +x /usr/local/bin/chromedriver \
    && rm /tmp/chromedriver.zip

# Set environment variables (optional)
ENV PATH="/usr/local/bin:$PATH"

# Set working directory
WORKDIR /app

# Copy your scraper code and requirements
COPY backend/scraping /app
COPY backend/api/requirements.txt /app/requirements.txt

# Upgrade pip and install Python dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt
